### ISSUE TITLE
должен называться просто addLast, зачем там слово Queue?

### ISSUE THREAD

**Issue by coursar** [burhon94/queue-any#1]
https://github.com/burhon94/queue-any/blob/46c3fabada2af0748fc39a1009f2d6e89c681e56/main.go#L33

**Comment by burhon94** [comment]
Думал так будет логичнее addLastQueue(добавить в конец очереди элемент), а так addLast(добавить в конец ) - куда, это было бы не более логичным хотя...

**Comment by burhon94** [comment]
Я думал, что было бы более логично (addLastQueue добавить в конец очереди элемент) , а  так (addLast добавить в конец ) - куда, это было бы не более логичным... хотя Вам виднее..
