### ISSUE TITLE
Надо тестировать не только размер, но и кто остался на первом, кто на последнем

### ISSUE THREAD

**Issue by coursar** [burhon94/queue-any#5]
https://github.com/burhon94/queue-any/blob/46c3fabada2af0748fc39a1009f2d6e89c681e56/main_test.go#L5-L91

Общий сценарий для пустой очереди:
1. Проверяете, что размер пустой очереди - 0
1. Добавляете один элемент
1. Удостоверяетесь, что первый - это тот, что вы добавили, последний - он же, размер = 1

Негативные проверки для пустой очереди (сделать отдельным тестом):
1. Проверяете, что будет, если попросить первого
1. Проверяете, что будет, если попросить последнего
1. Проверяете, что будет, если попробовать удалить последнего

По аналогии - с одним элементом и несколькими

**Comment by burhon94** [comment]
Check fixes, pls.
